apiVersion: v1
data:
  service-ca.crt: |+
    -----BEGIN CERTIFICATE-----
    MIIDUTCCAjmgAwIBAgIIbCLfGVB/xnUwDQYJKoZIhvcNAQELBQAwNjE0MDIGA1UE
    Awwrb3BlbnNoaWZ0LXNlcnZpY2Utc2VydmluZy1zaWduZXJAMTYwMzQyMjM0NDAe
    Fw0yMDEwMjMwMzA1NDRaFw0yMjEyMjIwMzA1NDVaMDYxNDAyBgNVBAMMK29wZW5z
    aGlmdC1zZXJ2aWNlLXNlcnZpbmctc2lnbmVyQDE2MDM0MjIzNDQwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCfDBDom6LBCtQ7Eg+Kr0c6jg5MqlgeT15m
    QqwoRd8NGjJSukw6I1dhgT65qkq+V70lOeTnNa5Bk5gT8TggbW0Id36FPafuq7kk
    tetPzl8SzXMLmBFWl5PUzNKflW0FoeRsFvJnBZ4E8RosJ/G3yRFK5evSU/HDFukO
    QjyBBcP8JPXKpueosz9elyvDm9qqwpkpSnJSuVubxyMYmv2+Dsny+VYI/S/SuQT+
    zmxvIFer5VfNxRUP6OUrJcrF2ENLgTMoS7Zx6DFAr8BkjdUKmH4EUJp8NZwrRqan
    ty4WWh8lEFweevQklyGwdKJLz7K2YD4Wq6bw9xBhZgq2TNKBORJ9AgMBAAGjYzBh
    MA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBS0g0Is
    pdK5054Yqud6RDF9DpPoMTAfBgNVHSMEGDAWgBS0g0IspdK5054Yqud6RDF9DpPo
    MTANBgkqhkiG9w0BAQsFAAOCAQEAQoqBLPFrhyq7ElIjrqYFmM21muUkb1QCk5kF
    7jb+Rr0+kn1dQgM/abS6JXeUJ4mY2OFrFqZNilI2t9z/k3Safst39ckiFqV+bJCK
    K3v+2Sq+XFnesGiFTf2tA9W5F77O62xwwlCV/zU0Tl4qu5lBSH1rAPPZAMeWIEqX
    +eXIcp1++fAnZ1tmf8R83GzQ84pblGinBjvwuyCuFCMU41J2NmEfHmtKBvWIPAcV
    mLNqHUmejQXv/QZHttrqzwKhqe9jIUH5OMHuPXbgZbdBQlbqlKCzISbCRKZZyB8y
    fcAM3Inm5jrHF4dj4CVkQuzLW59wCWhSLRcxNvuxThCF2UmCrg==
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDMjCCAhqgAwIBAgIIIIOyzCIE1BkwDQYJKoZIhvcNAQELBQAwNzESMBAGA1UE
    CxMJb3BlbnNoaWZ0MSEwHwYDVQQDExhrdWJlLWFwaXNlcnZlci1sYi1zaWduZXIw
    HhcNMjAxMDIzMDI1NTI3WhcNMzAxMDIxMDI1NTI3WjA3MRIwEAYDVQQLEwlvcGVu
    c2hpZnQxITAfBgNVBAMTGGt1YmUtYXBpc2VydmVyLWxiLXNpZ25lcjCCASIwDQYJ
    KoZIhvcNAQEBBQADggEPADCCAQoCggEBAMm9j7c2sgAMizosT5/9IPYexw3RAyNh
    iF89mUeeLXxCji/cXg56O81Rx4a87EaVy4w1tFyO4+jOMh4ic7rbHJElVY7931YY
    Zon6tlfQbEgUqvAMlbo6nATQSzvAxagBZ3o31SB//c3/iN9DRhI39qTYMoTRElSu
    mb0TnCXhTKp1QbQIlaA4qnbOEvONZr+sNlqLA3FuPAvAj3fUOOXJVnVaKP5ZaFYi
    eNI+u7ETV90hpj+8nX4mCtgpE5mV3gahFzW2uoCZRc6umxUR0zT8E5AaIIH85nN3
    02LwpAC8hu8DUqxuaMYIGSo7mHhnuqvLb6JdhLoYr+HZ5eWofqmDuvECAwEAAaNC
    MEAwDgYDVR0PAQH/BAQDAgKkMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFKHs
    u4LXh6DTaZ1mifOT+pew9GTgMA0GCSqGSIb3DQEBCwUAA4IBAQBrvm2hZXHZYbPo
    RyDUqSJQZMC+ip/ypCKKiCPbf0nScJDedc8/fsMJT9WA95O9+A5OaH+I1eu4vGRt
    YzZ1CXi213/cPG0HGu2ICot79bRqN2ZR2tQFzIJvhkq7w9PhE7uKNH+xp94cl1pg
    95+jfXIwZ2YZNFXoyXTDP+Opbj72CjZtMa27j3s36/vF8tBqQ7QbceOWa4TFZucn
    awEwN+A6ymo4tpAtC0rQaamegnojSz4I0TUGs0ROHP72RY631aAzrvMV2V9clAeX
    0AXeNNEB9VOg00D2c4wg+Rb73hHiyY2pzRBehG//YaggWUODYAn1VZBkrnr1Qifd
    qDuvFU9m
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDQDCCAiigAwIBAgIIf9W5KcsDAsEwDQYJKoZIhvcNAQELBQAwPjESMBAGA1UE
    CxMJb3BlbnNoaWZ0MSgwJgYDVQQDEx9rdWJlLWFwaXNlcnZlci1sb2NhbGhvc3Qt
    c2lnbmVyMB4XDTIwMTAyMzAyNTUyN1oXDTMwMTAyMTAyNTUyN1owPjESMBAGA1UE
    CxMJb3BlbnNoaWZ0MSgwJgYDVQQDEx9rdWJlLWFwaXNlcnZlci1sb2NhbGhvc3Qt
    c2lnbmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwTZ3xsUElN8C
    h5FFe5UK4uwKkGaPBbgK1Eczm9MBZZy1ceNHChmy9XN+yoik50cqu8hCVRbjFNuO
    DI2UXtSrRug5tQPyofVFbuf9TGyKj1Cx/cbJCis3r3BkiyeVeybYtzDozAMl+m56
    oC5rZEUVjxW0HDDntUbK4sgdP+pcdCI8zkZMWpbuVY0x+4/vTiB4ed7ulMm+QxLK
    KKoktL1xNKckVZThjP8xTwEg44xh1pHKzMvCnMAnlIyA74+Nr4TMQKF5sCh6zdP+
    4aLCZY9VYVKEYeJMnNCkcEHlMrxFTLayfS4U4SyB9BI5pszul2B/XFNi1SaECx5+
    7BygHeOfOwIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/BAUwAwEB
    /zAdBgNVHQ4EFgQUnJ+Ety7k1ksmAuCI0t0e3bUWBqEwDQYJKoZIhvcNAQELBQAD
    ggEBAJCzBom1/sL1S17/h2BU3GoZsE0pIKBd5ODtnhC4sl09fb7LTeo7zyl58cLh
    LCLhMG5eY5nP+/MfySeDnS+iFHXGz/6vB82l8LVJCAGl/74esSkWVP3m69DFMAcZ
    H+Bj041SYtopUddA3HSkTWOQ3OMXCJKNq9MnumfYBW4eLGiURM91XWLKGkTTEKLn
    gmAqTv0jnjvV4PWYwT5gpQwA4dIrFvaiUfjA0KiHH0uFAAUEpqkrwhlc7jnlHlQd
    T8sWz6PiTZH25UEaMwp0prP5O5pXBLaweAZjfD+7+SZLqMyQTuG/3xKalym0Jm3N
    63vNCeN2ER7Qt39913tdqmt6IAg=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDTDCCAjSgAwIBAgIICO2CX2vDTL4wDQYJKoZIhvcNAQELBQAwRDESMBAGA1UE
    CxMJb3BlbnNoaWZ0MS4wLAYDVQQDEyVrdWJlLWFwaXNlcnZlci1zZXJ2aWNlLW5l
    dHdvcmstc2lnbmVyMB4XDTIwMTAyMzAyNTUyN1oXDTMwMTAyMTAyNTUyN1owRDES
    MBAGA1UECxMJb3BlbnNoaWZ0MS4wLAYDVQQDEyVrdWJlLWFwaXNlcnZlci1zZXJ2
    aWNlLW5ldHdvcmstc2lnbmVyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
    AQEAwbrA3uQ914PuSJWoCXrZ0z/Ks38osqhVfj4HqtaBOEBopbJ6yqxWxff7zdMV
    YqD3hocUHJ/I7Ncd158n3gF/PI+KdHffBrDaXHuA4qMOVOU0xPQNtCCS21jQ1n1G
    VPqi6WBp4dOVd0JOe6mxXhO0ymAun3XAmz9jNpUeE+39qr1O2D76NbG3vVn8T1Xr
    bO4S2pyzd1FjkvhwCs09f7Ypb6RFlypuNgx0HipCmb9nrHlAjlPFiCvWkBwEO8mq
    qRgALZbyCigeirqlUyaKzzrt1RSO0jayVHRUs2xyotOu67qhV1wgRaBulpZTEZzc
    Qp2JcocI9D5tXg5NONFUTrexUwIDAQABo0IwQDAOBgNVHQ8BAf8EBAMCAqQwDwYD
    VR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQUk75QgkqtjUdTpdkVNUwndM/NmYgwDQYJ
    KoZIhvcNAQELBQADggEBAGxQ5vbJ7h73I140ajHdhgPqZeI/2OWexX9G9Q3085Wm
    6ITj5E7rGYWrz4dHB0Cs8r/3nB0M99hRRXjFHyzp+MsE58/j4krxTEAYVpcZr91S
    x/xi/d039h+XtAzYxnPXMRa7LFMOP95YArMYcOLwX2L6aymgDaAAzGArKQOzHFwG
    ztNV4CeIUt68z2aeZon7srv2rWQT3mhddJUwJis8rEbxZufKU6XaoBdC/N3c/cax
    Y5QvSM09Bw7P8bj1jjgBGd8IkzGzevn6x2jVwdvQwL3iTP4b5kgAgFrfKcfVBU7s
    xz8MhZvD106NFkv1C6gyhnB7F43/bvpcx2M/T+Fcc0Q=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDlzCCAn+gAwIBAgIIM7Jm3II/pW8wDQYJKoZIhvcNAQELBQAwWTFXMFUGA1UE
    AwxOb3BlbnNoaWZ0LWt1YmUtYXBpc2VydmVyLW9wZXJhdG9yX2xvY2FsaG9zdC1y
    ZWNvdmVyeS1zZXJ2aW5nLXNpZ25lckAxNjAzNDIyMzM3MB4XDTIwMTAyMzAzMDUz
    NloXDTMwMTAyMTAzMDUzN1owWTFXMFUGA1UEAwxOb3BlbnNoaWZ0LWt1YmUtYXBp
    c2VydmVyLW9wZXJhdG9yX2xvY2FsaG9zdC1yZWNvdmVyeS1zZXJ2aW5nLXNpZ25l
    ckAxNjAzNDIyMzM3MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3UX1
    BEYuBnepeUMMmQ2GtzVy1aEdymORwCXNNOaHr8qeDrcsgq4J+tJMinTOoaBjiOyo
    B1BMNYNOqadR/U7l7r56hINpQESxz13H+hw8F33PcpVAD6M2bcbnmzvId8B9Vpv/
    wYy2SdCt9Wr+U6KKmGN3QfMDs3sYJRQtL8LGecz+sbhaOM3nGPtiyTCwVQSthTWu
    VqQhUvdqa1P5yAkHshsMCpehQQeNkpcpkvdz/RTx7EeUO+DSA8Mzcq7IzVFHCmmy
    UPLeooU5a8T76WNLkkt86czO2OK69C7si5LaKwP7pHwqXBOnJP9bD/l8QPOTsiGZ
    zNnIUcLgdDgUDUjvNwIDAQABo2MwYTAOBgNVHQ8BAf8EBAMCAqQwDwYDVR0TAQH/
    BAUwAwEB/zAdBgNVHQ4EFgQUfq2epaB6ERLwC7VS/5mdVHYGgewwHwYDVR0jBBgw
    FoAUfq2epaB6ERLwC7VS/5mdVHYGgewwDQYJKoZIhvcNAQELBQADggEBAIoTCalo
    gUlHcqdEe9yPbwnccA6PGr68Q5GZe1qL32HRpm0xTqIGX/ox1yvnq3TnDwnJ8eYW
    3RK6ffpZN+CKQldOfOJlwLQjcApWL6rc4XH6gEPYBzwtl6Lg8nbBptvdPpwC/4Sg
    264VB5oimM9oatCnOixkZetM9o2kB0wLxhBflNm4SvtFa4q9VpXd2iDjlFWKsKfv
    e14XzME9yII0NhxIXShFMPqWNuuMXptokbJDA9BLL0jpqd5ufLqdyxF1KqGasqJ6
    h+Fmgl8vayqsvAKU40V81jyzbAYhHeu2+Nwuh9JYWG3M4jNqklGGiqhGqAoxc5Rh
    YKgNAEs/AsQXYq0=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFpDCCBIygAwIBAgISBGdFQ0cxRGt6nQG24r7y2qV5MA0GCSqGSIb3DQEBCwUA
    MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
    EwJSMzAeFw0yMTA3MTUwOTU3MDJaFw0yMTEwMTMwOTU3MDFaMDAxLjAsBgNVBAMT
    JWFwaS5zYW5kYm94Lng4aTUucDEub3BlbnNoaWZ0YXBwcy5jb20wggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDDLiB4oyLAvOOlCE4+or1B/wrgD3ComJ63
    PWxaSGtQvUez2jDVAnxO4U7+bO+vkv0BcKscDNlTa9udBa4E+/hNoWOJZUCawNlR
    4AIoy7lriGwyf9H/8AMYA1ewn0pth/qfXbC+l1w8WAEq1nbAPhmEPtqF0wkB8Qaq
    KAIXv78UUuDhQKXBLCDaPn5DGl2tJ0KIU8a0LrXp3qUrW35VT13MDJNYpdT9mW9q
    /HqBuJ4RdNH2kpx8IxVeDRLS0GJejENNcDOlifu1XleFUamRcXuCz3X+yQdBp2hW
    9g6fvYyAcAxtxXMrAxzitgyF6DkorHQHTIpRJgc26UGlk8WZkFkZAgMBAAGjggK0
    MIICsDAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUF
    BwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0OBBYEFKZIZnDGfkDKiIhsET/fT9Reg4AE
    MB8GA1UdIwQYMBaAFBQusxe3WFbLrlAJQOYfr52LFMLGMFUGCCsGAQUFBwEBBEkw
    RzAhBggrBgEFBQcwAYYVaHR0cDovL3IzLm8ubGVuY3Iub3JnMCIGCCsGAQUFBzAC
    hhZodHRwOi8vcjMuaS5sZW5jci5vcmcvMIGEBgNVHREEfTB7gigqLmFwcHMuc2Fu
    ZGJveC54OGk1LnAxLm9wZW5zaGlmdGFwcHMuY29tgiVhcGkuc2FuZGJveC54OGk1
    LnAxLm9wZW5zaGlmdGFwcHMuY29tgihyaC1hcGkuc2FuZGJveC54OGk1LnAxLm9w
    ZW5zaGlmdGFwcHMuY29tMEwGA1UdIARFMEMwCAYGZ4EMAQIBMDcGCysGAQQBgt8T
    AQEBMCgwJgYIKwYBBQUHAgEWGmh0dHA6Ly9jcHMubGV0c2VuY3J5cHQub3JnMIIB
    AwYKKwYBBAHWeQIEAgSB9ASB8QDvAHYAlCC8Ho7VjWyIcx+CiyIsDdHaTV5sT5Q9
    YdtOL1hNosIAAAF6qdAP4wAABAMARzBFAiEA3mzwiBeke+GpgyTHpufuIrBHh+DR
    1apiyybkAMTYGUgCIB9kUqdOn9GsgMwFsrEHyN6xthxBZXXhVk7vQH4XbuGQAHUA
    9lyUL9F3MCIUVBgIMJRWjuNNExkzv98MLyALzE7xZOMAAAF6qdAP4gAABAMARjBE
    AiBM5UJrWh5or1QmzB4B7JogkPMTRjLnQYhbEVRb23gPNwIgbeqcB/ubKu5QQA2F
    cFLFN8xf0LJZL3MQt2kpp2SPmkswDQYJKoZIhvcNAQELBQADggEBAJ7DEOUHw0JT
    4p1QN28E+usRdLu5CuzEZ0amKTDwCn+VfzDvgeWavBo/vkdGxi3BrpWdZowUP7S1
    dn+Wa69IiO1P4HI19JDdkF/Q5oCuDqd1j25jrS6oBUyxsgMh4XxF5+aEcb05W0bo
    F6e9/VjBukOj/PkROealOkjv6eULVd9Bd9zQUeVXbpNdTV7kA/yBHQ1T6iNcxa+j
    yzMMcAAsdawBFsf+rIaHhf7XxqkRm9Rb0xiTc4BhlbTHw1voPlx/dhL3TMiqW1Ft
    R5ryV7dIZ5aTcyiul1/GUQqMMAunHJqDWUdHR/mIQrFgEg+H37iQ3dYnSjttEpCz
    U+jYYccN1zo=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
    TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
    cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
    WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
    RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
    AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
    R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
    sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
    NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
    Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
    /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
    AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
    Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
    FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
    AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
    Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
    gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
    PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
    ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
    CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
    lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
    avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
    yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
    yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
    hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
    HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
    MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
    nLRbwHOoq7hHwg==
    -----END CERTIFICATE-----

kind: ConfigMap
metadata:
  annotations:
    service.alpha.openshift.io/inject-vulnerable-legacy-cabundle: "true"
  name: openshift-service-ca.crt
  namespace: jduimovich-dev
