apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    container.apparmor.security.beta.kubernetes.io/fib-quarkus-deploy: runtime/default
  labels:
    app: fib
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: fib-service-in-quarkus
    app.kubernetes.io/name: fib-quarkus-deploy
    app.kubernetes.io/part-of: fib-service
    app.openshift.io/runtime: quarkus
  name: fib-quarkus-deploy
  namespace: jduimovich-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fib
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fib
    spec:
      containers:
        - image: quay.io/jduimovich0/fib-quarkus:demo
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /fib
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 1
          name: fib-quarkus-deploy
          ports:
            - containerPort: 8080
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 200m
              memory: 384Mi
            requests:
              cpu: 100m
              memory: 384Mi
          securityContext:
            capabilities:
              drop:
                - all
            readOnlyRootFilesystem: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      terminationGracePeriodSeconds: 30
