apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: frontend-service
  name: frontend-service
  namespace: jduimovich-dev
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: frontend
  sessionAffinity: None
  type: ClusterIP
