apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app: haproxy-service
  name: haproxy-service
  namespace: jduimovich-dev
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: haproxy
  sessionAffinity: None
  type: ClusterIP
